{
 "title": "Sfedu grade monitoring dashboard",
 "time": { "from": "2022-04-26T03:00:08.773Z", "to": "2022-05-12T19:22:04.183Z" },
 "panels": [
  { "title": "Matomo monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Визит/мин.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "select \r\ntoStartOfInterval(visit_last_action_time,Interval 1 minute) as bucket\r\n--,sum(visit_total_actions)\r\n--,sum(visit_total_time)\r\n,count(1) as \"Визит/мин.\"\r\nfrom matomo.matomo_log_visit\r\n--where toDate(visit_first_action_time) = '2022-04-26'\r\ngroup by bucket\r\norder by bucket"
    }
   ]
  },
  {
   "title": "Устройства",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select config_os ,count(1) as cnt \r\nfrom matomo.matomo_log_visit mlv\r\nwhere toDate(visit_last_action_time) = (select max(toDate(visit_last_action_time)) from matomo.matomo_log_visit)\r\ngroup by config_os\r\norder by cnt desc"
    }
   ]
  },
  {
   "title": "Суточная активность",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select toStartOfInterval(server_time ,Interval 1 day) as bucket\r\n,idvisitor\r\n--,idvisit\r\n, count(1) as cnt\r\nfrom matomo.matomo_log_link_visit_action\r\nwhere server_time >= (select max(toDate(server_time)) from matomo.matomo_log_link_visit_action)\r\ngroup by bucket,idvisitor,idvisit\r\norder by bucket desc, cnt desc\r\nlimit 50"
    }
   ]
  },
  {
   "title": "Действия/сек.",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select idvisitor,sum(visit_total_actions/(visit_total_time+1)) as sum from matomo.matomo_log_visit\r\nwhere toDate(visit_last_action_time) = (select max(toDate(visit_last_action_time)) from matomo.matomo_log_visit)\r\ngroup by idvisitor\r\norder by sum desc"
    }
   ]
  },
  {
   "title": "Действия/мин.",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select toStartOfInterval(server_time ,Interval 1 minute) as bucket\r\n--,idvisit\r\n--,idaction_name \r\n,count(*) as cnt\r\nfrom matomo.matomo_log_link_visit_action\r\nwhere toDate(server_time) = (select max(toDate(server_time)) from matomo.matomo_log_link_visit_action)\r\ngroup by bucket--,idaction_name \r\norder by bucket desc, cnt desc\r\nlimit 1"
    }
   ]
  },
  {
   "title": "Действия",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) \r\nfrom matomo.matomo_log_link_visit_action mllva \r\nwhere toDate(server_time) = (select max(toDate(server_time)) from matomo.matomo_log_link_visit_action)\r\n"
    }
   ]
  },
  {
   "title": "Визит/мин.",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select toStartOfInterval(server_time ,Interval 1 minute) as bucket\r\n--,idvisit\r\n--,idaction_name \r\n,count(distinct idvisit) as cnt\r\nfrom matomo.matomo_log_link_visit_action\r\nwhere toDate(server_time) = (select max(toDate(server_time)) from matomo.matomo_log_link_visit_action)\r\ngroup by bucket--,idaction_name \r\norder by bucket desc, cnt desc\r\nlimit 1"
    }
   ]
  },
  {
   "title": "Визиты",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count( DISTINCT idvisit)\r\nfrom matomo.matomo_log_link_visit_action\r\nwhere toDate(server_time) = (select max(toDate(server_time)) from matomo.matomo_log_link_visit_action)"
    }
   ]
  },
  {
   "title": "Локации активности",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 18, "x": 3, "y": 17 },
   "targets": [
    {
     "rawSql": "select idvisit ,location_latitude, location_longitude \r\nfrom matomo.matomo_log_visit\r\nwhere toDate(visit_last_action_time) = (select max(toDate(visit_last_action_time)) from matomo.matomo_log_visit)"
    }
   ]
  },
  {
   "title": "Web logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Запросы",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "rawSql": "select \r\ntoStartOfInterval(dtlogged,Interval 1 minute) as \"Интервал\"\r\n,count(1) as \"Запросы/мин.\"\r\nfrom test_db.detailed_logs\r\nwhere 1=1\r\nand vcstatus = 'INFO'\r\ngroup by \"Интервал\"\r\norder by \"Интервал\""
      }
     ]
    },
    {
     "title": "Самые длительные запросы",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select toDate(dtlogged) as dtlogged \r\n, extract(vcpath, '.*/(.*)') as class\r\n, avg(dduration) as avg_dur\r\n, count(*) as cnt\r\nfrom test_db.detailed_logs l\r\nwhere vcstatus = 'INFO'\r\nand class <> ''\r\nand dtlogged = (select max(toDate(dtlogged)) from test_db.detailed_logs)\r\ngroup by dtlogged, vcstatus, vctype, vcpath--limit 1000\r\norder by avg_dur desc\r\nlimit 100"
      }
     ]
    },
    {
     "title": "Статусы",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
     "targets": [
      {
       "rawSql": "select vcstatus,count(1)\r\nfrom test_db.detailed_logs\r\nwhere 1=1\r\nand toDate(dtlogged) = (select max(toDate(dtlogged)) from test_db.detailed_logs)\r\ngroup by vcstatus"
      }
     ]
    },
    {
     "title": "Ошибки",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "rawSql": "select formatDateTime(dtlogged,'%Y-%m-%d') as \"Дата\", vctype as \"Тип\", vcdesc as \"Описание\", count(1) as \"Кол-во\"\r\nfrom test_db.detailed_logs dl \r\nwhere vcstatus = 'EMERGENCY'\r\nGROUP BY \"Дата\",\"Тип\",\"Описание\"\r\norder by \"Дата\" asc,\"Кол-во\" desc\r\n"
      }
     ]
    },
    {
     "title": "Топ ошибок",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select toDate(dtlogged) as dtlogged\r\n, vctype\r\n, count(1) as cnt\r\nfrom test_db.detailed_logs dl \r\nwhere vcstatus = 'EMERGENCY'\r\nand dtlogged = (select max(toDate(dtlogged)) from test_db.detailed_logs)\r\nGROUP BY dtlogged,vctype \r\norder by dtlogged asc,cnt desc"
      }
     ]
    },
    {
     "title": "Предупреждения",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "rawSql": "select formatDateTime(dtlogged,'%Y-%m-%d') as \"Дата\", vctype as \"Тип\", count(1) as \"Кол-во\"\r\nfrom test_db.detailed_logs dl \r\nwhere vcstatus = 'WARNING'\r\nGROUP BY \"Дата\",\"Тип\"\r\norder by \"Дата\" asc,\"Кол-во\" desc\r\n"
      }
     ]
    },
    {
     "title": "Топ предупреждений",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select toDate(dtlogged) as dtlogged\r\n, vctype\r\n, count(1) as cnt\r\nfrom test_db.detailed_logs dl \r\nwhere vcstatus = 'WARNING'\r\nand dtlogged = (select max(toDate(dtlogged)) from test_db.detailed_logs)\r\nGROUP BY dtlogged,vctype \r\norder by dtlogged asc,cnt desc"
      }
     ]
    }
   ]
  }
 ]
}